### PR TITLE
Add support for React 16

### PR DESCRIPTION
**Pull request by emmaffiondavies**
~Blocked on https://github.com/BluewireTechnologies/epro/pull/3629.~ (Dependency removed)
~Blocked on https://github.com/BluewireTechnologies/epro/pull/3676.~ (Merged)

E-28662

### CODE REVIEW

**Comment by emmaffiondavies** [comment]
~Don't merge yet; this isn't quite working...~ (Fixed)

**Comment by emmaffiondavies** [comment]
This appears to be fixed now although won't know for definite until https://github.com/BluewireTechnologies/epro/pull/3629 is complete as it's not possible to start Epro Modern at the moment to be able to smoke test the drawing module. Can be optimistically reviewed by @luckyrat in the meantime.

**Review by luckyrat — COMMENTED** [review]
Seems fine - as you say, the proof is in the pudding for a change like this really.

There're two ways we can go about this:
1) Support both react 15 and 16
2) Support only 16

If (2), we'd want to update package.json but it would be good if we can get (1) working - you would have to test the library in both 15 and 16 though which might add a bit of overhead that dala might want to consider signing off on.

**Comment by emmaffiondavies** [comment]
> @luckyrat: _"...Support both react 15 and 16..."_

Why would we want to do that out of curiosity?

**Comment by luckyrat** [comment]
> Why would we want to do that out of curiosity?

Two reasons:
1) If we want this PR to be accepted into an upstream library, providing a smooth migration path for other library users could be essential. IMO, the benefits of open source contribution would outweigh some extra testing cost, although to what scale is open for debate.
2) We could choose to merge the build output from this change into master in advance of the switch to React 16, potentially reducing the size of the React 16 PR and aiding in attribution of unexpected bugs to either this part of the upgrade or other React 16 changes. Again, the pros and cons can make for an interesting debate.

All things considered I'd go for the incremental approach with extra testing and possibility of OS contribution at the end but that's not without an element of risk and cost so would be up to Damien or Doug to decide I guess.

**Comment by emmaffiondavies** [comment]
> @luckyrat: _"If we want this PR to be accepted into an upstream library, providing a smooth migration path for other library users could be essential. IMO, the benefits of open source contribution would outweigh some extra testing cost, although to what scale is open for debate."_

I was planning on submitting something subtly different to the main LC repo and will be able to verify it works with React 14-16 as they have a built-in demo app in their repo.

> @luckyrat: _"We could choose to merge the build output from this change into master in advance of the switch to React 16, potentially reducing the size of the React 16 PR and aiding in attribution of unexpected bugs to either this part of the upgrade or other React 16 changes. Again, the pros and cons can make for an interesting debate."_

Ah, I see what you mean! Sure, I can submit a separate PR for the `createReactClass()` changes. I'd planned to do that in [E-28664](https://jira.epro.com/browse/E-28664) but deemed at the time that it was no longer necessary although it obviously now transpires that that assertion wasn't quite correct...

**Comment by emmaffiondavies** [comment]
@luckyrat: I've filed https://github.com/BluewireTechnologies/epro/pull/3676 to verify the LC changes don't break anything with Epro running on React 15.

**Pull request merged**
